 
 --criando a tabela País 
 CREATE TABLE VEMSER_PATRICIA.PAIS (
    ID_PAIS NUMBER (38) NOT NULL,
    NOME VARCHAR2(50) UNIQUE NOT NULL,
    PRIMARY KEY (ID_PAIS)
 );

 --criando a tabela Estado 
 CREATE TABLE VEMSER_PATRICIA.ESTADO(
    ID_ESTADO NUMBER (38) NOT NULL,
    ID_PAIS NUMBER (38) NOT NULL,
    NOME VARCHAR2(50) UNIQUE NOT NULL,
    PRIMARY KEY (ID_ESTADO)
 );

 --restrição: id_pais como chave estrangeira e referencia a tabela pais DENTRO DA TABELA ESTADO
 ALTER TABLE VEMSER_PATRICIA.ESTADO 
   ADD CONSTRAINT FK_PAIS FOREIGN KEY (ID_PAIS) 
   REFERENCES VEMSER_PATRICIA.PAIS(ID_PAIS);
  

 --criando a tabela Cidade 
 CREATE TABLE VEMSER_PATRICIA.CIDADE(
    ID_CIDADE NUMBER (38) NOT NULL,
    ID_ESTADO NUMBER (38) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    PRIMARY KEY (ID_CIDADE, ID_ESTADO)
 );

 --restrição: id_estado como chave estrangeira e referencia a tabela estado DENTRO DA TABELA CIDADE

 ALTER TABLE VEMSER_PATRICIA.CIDADE 
   ADD CONSTRAINT FK_ESTADO FOREIGN KEY (ID_ESTADO) 
   REFERENCES VEMSER_PATRICIA.ESTADO(ID_ESTADO);
  
  
 --criando a tabela Bairro
 CREATE TABLE VEMSER_PATRICIA.BAIRRO(
    ID_BAIRRO NUMBER (38) NOT NULL,
    ID_CIDADE NUMBER (38) NOT NULL,
    ID_ESTADO NUMBER (38) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    PRIMARY KEY (ID_BAIRRO, ID_CIDADE)
 );

 --restrição: id_estado e id_cidade como chave estrangeira e referencia a tabela estado e tabela cidade DENTRO DA TABELA BAIRRO

 ALTER TABLE VEMSER_PATRICIA.BAIRRO 
   ADD CONSTRAINT FK_ESTADO_CIDADE FOREIGN KEY (ID_ESTADO, ID_CIDADE) 
   REFERENCES VEMSER_PATRICIA.CIDADE(ID_ESTADO, ID_CIDADE);
  
 --criando a tabela Endereço
 CREATE TABLE VEMSER_PATRICIA.ENDERECO(
    ID_ENDERECO NUMBER (38) NOT NULL,
    ID_BAIRRO NUMBER (38) NOT NULL,
    ID_CIDADE NUMBER (38) NOT NULL,
    LOGRADOURO VARCHAR2 (255) NOT NULL,
    NUMERO NUMBER (38) NOT NULL,
    COMPLEMENTO VARCHAR2 (100),
    CEP CHAR (9),
    PRIMARY KEY (ID_ENDERECO)
 );  

 --restrição: id_bairro e id_cidade como chave estrangeira e referencia a tabela bairro e tabela cidade DENTRO DA TABELA ENDERECO

 ALTER TABLE VEMSER_PATRICIA.ENDERECO 
   ADD CONSTRAINT FK_BAIRRO_CIDADE FOREIGN KEY (ID_BAIRRO, ID_CIDADE) 
   REFERENCES VEMSER_PATRICIA.BAIRRO(ID_BAIRRO, ID_CIDADE);
  
  -- CRIANDO AS SEQUENCES DE CADA TABELA
  
   CREATE SEQUENCE SEQ_PAIS
     START WITH     1
     INCREMENT BY   1
     NOCACHE 
     NOCYCLE; 
    
   CREATE SEQUENCE SEQ_ESTADO
     START WITH     1
     INCREMENT BY   1
     NOCACHE 
     NOCYCLE; 
    
   CREATE SEQUENCE SEQ_CIDADE
     START WITH     1
     INCREMENT BY   1
     NOCACHE 
     NOCYCLE; 

   CREATE SEQUENCE SEQ_BAIRRO
     START WITH     1
     INCREMENT BY   1
     NOCACHE 
     NOCYCLE;     
    
   CREATE SEQUENCE SEQ_ENDERECO
     START WITH     1
     INCREMENT BY   1
     NOCACHE 
     NOCYCLE; 
    
  -- INICIANDO OS INSERTS
 
  -- Países
  INSERT INTO VEMSER_PATRICIA.PAIS (ID_PAIS, NOME)
     VALUES(SEQ_PAIS.nextval, 'Brasil');   
  
  INSERT INTO VEMSER_PATRICIA.PAIS (ID_PAIS, NOME)
     VALUES(SEQ_PAIS.nextval, 'Canadá');     

 -- Estados
 INSERT INTO VEMSER_PATRICIA.ESTADO (ID_ESTADO, ID_PAIS, NOME)
    VALUES(SEQ_ESTADO.nextval, 1, 'Rio Grande do Sul');   
 
 INSERT INTO VEMSER_PATRICIA.ESTADO (ID_ESTADO, ID_PAIS, NOME)
    VALUES(SEQ_ESTADO.nextval, 1, 'São Paulo');    
  
 INSERT INTO VEMSER_PATRICIA.ESTADO (ID_ESTADO, ID_PAIS, NOME)
    VALUES(SEQ_ESTADO.nextval, 2, 'Quebec');   
 
 INSERT INTO VEMSER_PATRICIA.ESTADO (ID_ESTADO, ID_PAIS, NOME)
    VALUES(SEQ_ESTADO.nextval, 2, 'Ontário');  
 
 -- Cidades
 INSERT INTO VEMSER_PATRICIA.CIDADE (ID_CIDADE, ID_ESTADO, NOME)
    VALUES(SEQ_CIDADE.nextval, 1, 'Porto Alegre');   
   
 INSERT INTO VEMSER_PATRICIA.CIDADE (ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_CIDADE.nextval, 1, 'Alegrete'); 
  
 INSERT INTO VEMSER_PATRICIA.CIDADE (ID_CIDADE, ID_ESTADO, NOME)
    VALUES(SEQ_CIDADE.nextval, 2, 'São Paulo');   
   
 INSERT INTO VEMSER_PATRICIA.CIDADE (ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_CIDADE.nextval, 2, 'Taubaté');      
   
 INSERT INTO VEMSER_PATRICIA.CIDADE (ID_CIDADE, ID_ESTADO, NOME)
    VALUES(SEQ_CIDADE.nextval, 3, 'Quebec');   
   
 INSERT INTO VEMSER_PATRICIA.CIDADE (ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_CIDADE.nextval, 3, 'Montreal');       
  
 INSERT INTO VEMSER_PATRICIA.CIDADE (ID_CIDADE, ID_ESTADO, NOME)
    VALUES(SEQ_CIDADE.nextval, 4, 'Toronto');   
   
 INSERT INTO VEMSER_PATRICIA.CIDADE (ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_CIDADE.nextval, 4, 'Ottawa');       
  
  
 --Bairros
  
 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 1, 1, 'Partenon'); 
  
 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 1, 1, 'Três Figueiras');    

 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 2, 1, 'Ibirapuitã');    

 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 2, 1, 'Centro');    
  
 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 3, 2, 'Vila Mariana');      
  
 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 3, 2, 'Liberdade');        
  
 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 4, 2, 'Bom Conselho');      

 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 4, 2, 'Chafariz');     
  
 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 5, 3, 'Old Quebec');  
  
 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 5, 3, 'Place Royale');      
  
 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 6, 3, 'Old Montreal');      
    
 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 6, 3, 'Downtown');        
  
 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 7, 4, 'The Beach');  
  
 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 7, 4, 'Old Town Toronto');     
  
 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 8, 4, 'The Glebe');    

 INSERT INTO VEMSER_PATRICIA.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME)
   VALUES(SEQ_BAIRRO.nextval, 8, 4, 'Chinatown Ottawa');     
  
  
 --Endereço 
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 1, 1, 'Rua C', 100, null , '99988-877');

 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 1, 1, 'Rua Bento Gonçalves', 800, 110 , '88899-877');
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 2, 1, 'Rua Nilo Peçanha', 900, 802 , '77788-877');  
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 2, 1, 'Rua Severo Dullius', 2000, null , '44488-877');    
    
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 3, 2, 'Rua Eurípedes Brasil Milano', 767, null, '66688-877');      
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 3, 2, 'Rua dos Patos', 120, null, '11188-877');    
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 4, 2, 'Rua Andradas', 409, null, '22288-877');   

 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 4, 2, 'Rua Dr. Flores', 900, null, '33388-877');  
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 5, 3, 'Rua Afonso Celso', 510, 302, '33388-456');    
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 5, 3, 'Rua José de Magalhães', 815, 509, '77788-456');    
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 6, 3, 'Rua Galvão Bueno', 1050, 201, '77799-456'); 
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 6, 3, 'Rua Almirante Mauriti', 800, 301, '99988-456');      
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 7, 4, 'Rua Carneiro de Souza', 13, 502, '11188-456');    

 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 7, 4, 'Rua Bento Vieira de Moura', 900, null, '22288-456');    
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 8, 4, 'Rua dos Operários', 304, null, '22288-800');     
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 8, 4, 'Rua Olavo Bilac', 600, 101, '22993-800');     
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 9, 5, 'Rue Petit-Champlain', 901, null, '55993-304');   

 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 9, 5, 'Rue Sous-le-Cap', 400, null, '55333-304'); 

 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 10, 5, 'Guy Street', 205, null, '52213-304');   
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 10, 5, 'Pine Avenue', 504, 10, '52441-501');    
 
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 11, 6, 'Jarry Street', 301, null, '58813-304');    

 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 11, 6, 'Notre-Dame Street', 403, 200, '53313-403');    
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 12, 6, '26th Street', 403, 580, '53224-403');        
 
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 12, 6, '25th Street', 1050, null, '52313-510');      
  
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 13, 7, '42th Street', 42, 401, '53331-403');        
 
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 13, 7, '39th Street', 500, null, '52313-250');      
    
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 14, 7, '6 Point Road', 309, 269, '53624-403');        
 
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 14, 7, '6th Street', 920, null, '59613-125');      
    
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 15, 8, 'Adair Road', 52, 69, '59974-403');        
 
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 15, 8, 'Adelaide Place', 145, null, '53613-852');      
    
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 16, 8, 'Beacon Road', 12, 14, '54424-114');        
 
 INSERT INTO VEMSER_PATRICIA.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP) 
   VALUES(SEQ_ENDERECO.nextval, 16, 8, 'Beaver Avenue', 178, null, '55613-510');      
    
  
  --CONSULTAS
  
  --Países ordenados por nome decrescente:
  SELECT * FROM VEMSER_PATRICIA.PAIS ORDER BY NOME DESC 
  
  --Logradouro e cep dos endereços. Porém somente os logradouros que comecem com a letra a maiúsculo ou minúsculo
  SELECT LOGRADOURO, CEP FROM VEMSER_PATRICIA.ENDERECO WHERE LOGRADOURO LIKE UPPER ('a%')
  
  --Enderecos que tenham cep com final 0
  SELECT * FROM VEMSER_PATRICIA.ENDERECO WHERE CEP LIKE '%0'

  --Enderecos que tenham número entre 1 e 100
  SELECT * FROM VEMSER_PATRICIA.ENDERECO WHERE NUMERO BETWEEN 1 AND 100
  
  --Enderecos que comecem por "rua" e ordenar cep de forma decrescente
  SELECT * FROM VEMSER_PATRICIA.ENDERECO WHERE LOGRADOURO LIKE 'Rua%' ORDER BY CEP DESC
  
  --Selecionar a quantidade de endereços cadastrados na tabela
  SELECT COUNT (*) "Quantidade de endereços: " FROM VEMSER_PATRICIA.ENDERECO
  
  --Selecionar a quantidade de endereços agrupados pela id da cidade 
  SELECT ID_CIDADE, COUNT (*) "Quantidade de endereços: " FROM VEMSER_PATRICIA.ENDERECO GROUP BY ID_CIDADE ORDER BY ID_CIDADE 