-----------------HOMEWORK #3----------------
	   
--RIGHT OUTER JOIN ENTRE:

	   --PESSOA E CONTATO
	   SELECT P.ID_PESSOA, P.NOME,
	   		  C.NUMERO
	   		  
	   		  FROM PESSOA P
	   		  RIGHT OUTER JOIN CONTATO C ON (C.ID_PESSOA = P.ID_PESSOA)
	   
	   --PESSOA, PESSOA X PESSOA ENDEREÇO E ENDERECO PESSOA
	   SELECT P.ID_PESSOA, P.NOME, 
	   		  PXPE.ID_ENDERECO,
	   		  EP.CIDADE, EP.ESTADO
	   		  
	   		  FROM PESSOA P
	   		  RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (PXPE.ID_PESSOA = P.ID_PESSOA)
	   		  RIGHT OUTER JOIN ENDERECO_PESSOA ep ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO)
	   		  
	   --TODAS AS TABELAS
	   SELECT P.ID_PESSOA, P.NOME,
	          C.NUMERO,
	          PXPE.ID_ENDERECO,
	          EP.CIDADE, EP.ESTADO, EP.PAIS
	          
	          FROM PESSOA P
	          RIGHT OUTER JOIN CONTATO c ON (C.ID_PESSOA = P.ID_PESSOA)
	          RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (PXPE.ID_PESSOA = P.ID_PESSOA)
	          RIGHT OUTER JOIN ENDERECO_PESSOA ep ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO)
	   			
--OUTER FULL JOIN ENTRE:	

	          --PESSOA E CONTATO
	          SELECT P.ID_PESSOA, P.NOME,
	          		 C.NUMERO, C.DESCRICAO
	          		 
	          		 FROM PESSOA P
	          		 FULL OUTER JOIN CONTATO c ON (C.ID_PESSOA = P.ID_PESSOA)
	          
	          --PESSOA, PESSOA X PESSOA ENDEREÇO E ENDEREÇO PESSOA
	          SELECT P.ID_PESSOA, P. NOME,
	          		 PXPE.ID_PESSOA,
	          		 EP.CEP, EP.CIDADE, EP.ESTADO, EP.PAIS
	          		 
	          		 FROM PESSOA P
	          		 FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (PXPE.ID_PESSOA = P.ID_PESSOA)
	          		 FULL OUTER JOIN ENDERECO_PESSOA ep ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO)
	          		    
	          --TODAS AS TABELAS
	          SELECT P.ID_PESSOA, P.NOME,
	          		 C.NUMERO, C.DESCRICAO,
	          		 PXPE.ID_ENDERECO,
	          		 EP.CEP, EP.CIDADE, EP.ESTADO, EP.PAIS
	          		 
	          		 FROM PESSOA P
	          		 FULL OUTER JOIN CONTATO c ON (C.ID_PESSOA = P.ID_PESSOA)
	          		 FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (PXPE.ID_PESSOA = P.ID_PESSOA)
	          		 FULL OUTER JOIN ENDERECO_PESSOA ep ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO)
	          		 
--UTILIZANDO EXISTS, SELECIONE AS PESSOAS QUE TEM ENDEREÇO
	          
	          SELECT P.ID_PESSOA, P.NOME AS "PESSOAS COM ENDEREÇO"	
	          		
	           		 FROM PESSOA P
	           		 WHERE EXISTS 
	           		 (
	           		   SELECT PXPE.ID_PESSOA  
	           		   FROM PESSOA_X_PESSOA_ENDERECO pxpe
	           		   WHERE PXPE.ID_PESSOA = P.ID_PESSOA
	           		 )
	          		 
--SELECIONE ID, NOME DA TABELA PESSOA JUNTO COM ID, LOGRADOURO DA TABELA ENDEREÇO
	          
	          SELECT P.ID_PESSOA, P.NOME,
	          		 EP.ID_ENDERECO, EP.LOGRADOURO
	          		 
	          		 FROM PESSOA p 
	          		 INNER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (PXPE.ID_PESSOA = P.ID_PESSOA)
	          		 INNER JOIN ENDERECO_PESSOA ep ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO)